config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  resources :tweets, only: %i[new create update]
  get :dashboard, to: "dashboard#index"
  resources :usernames, only: [:index, :new, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: { case_sensitive: false}, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :redirect_to_username_form, if: -> {user_signed_in? && current_user.username&.blank?}

    protected

    def after_sign_in_path_for(resource)
        dashboard_path
    end

    def redirect_to_username_form
        return if controller_name == 'usernames'
        redirect_to new_username_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to dashboard_path if user_signed_in?
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    protected
  
    def after_sign_up_path_for(resource)
      dashboard_path
    end
  end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def create
      @tweet = Tweet.new(tweet_params.merge(user: current_user))
  
      if @tweet.save
        redirect_to root_path
      else
        render :new
      end
    end
  
    private
  
    def tweet_params
      params.require(:tweet).permit(:content)
    end
  end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController 
    before_action :authenticate_user!
    before_action :set_user, only: [:update]
    skip_before_action :redirect_to_username_form

    def new
        @username = User.new
        end

    def update
        @user = User.find(params[:id])
        if @user.update(username_params)
            redirect_to dashboard_path
        else
            render dashboard_path
        end
    end

    private

    def username_params
        params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1> Welcome <%= current_user.email %> </h1>
<%= link_to "Sign out", destroy_user_session_path, data: {"turbo-method": :delete}, class: "btn btn-outline-primary btn-lg" %> 
<%= form_with model: Tweet.new, url: tweets#create, method: :post, local: true do |form| %>
    <%= form.text_field :content, class: "form-control", placeholder: "What's happening?" %>
    <%= form.submit "Tweet", class: "btn btn-primary btn-lg" %>
  <% end %>
  <ul>
  <% Tweet.find_each do |tweet| %>
    <li>
      <div class="card mt-3">
        <div class="card-body">
          <p><%= tweet.content %></p>
          <p><%= tweet.user.email %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/home/index.html.erb
    <h1> Hello world </h1>
    
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-primary btn-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usernames/new.html.erb
<div class="container-sm py-5" style="max-width: 540px">
  <h2> Set your username </h2>
  <%= form_with model: current_user, url: usernames_path, method: :post, local: true do |form| %>
    <div class="mb-3">
      <%= form.label :username %><br />
      <%= form.text_field :username, class: "form-control" %>
    </div>
    <div class="actions">
      <%= form.submit "Set username", class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
</div>